#!/bin/sh

RELEASE=${1:-prototype}
ASSET_DIR="marco_site/assets/"
STATIC_DIR="marco_site/static/"
REMOTE_ROOT="~/webapps/marco_portal2/site"
REMOTE_RESTART_CMD="~/webapps/marco_portal2/apache2/bin/restart"
CELERY_PIDFILE=$HOME/run/marco_portal2_celery.pid
CELERY_WORKER=$HOME/webapps/marco_portal2/site/scripts/celery-worker.sh

if [ "$2" == "prod" ]
  then
    REMOTE_HOST="point97@midatlantic.point97.io"
else
    REMOTE_HOST="point97@midatlantic-sandbox.point97.io"
fi

ssh $REMOTE_HOST << ENDSSH
cd $REMOTE_ROOT
git stash
git fetch
git checkout -f origin/$RELEASE
ENDSSH


# local
git stash
git fetch
git checkout -f origin/$RELEASE
cd $ASSET_DIR
npm install
./node_modules/.bin/gulp
./node_modules/.bin/webpack -p
cd -
rsync -avz --delete $STATIC_DIR $REMOTE_HOST:$REMOTE_ROOT/$STATIC_DIR
# restore previous branch
git checkout @{-1}
git stash pop


ssh $REMOTE_HOST << ENDSSH
cat $CELERY_PIDFILE | xargs kill
rm $CELERY_PIDFILE
source ~/env/marco_portal2/bin/activate
cd $REMOTE_ROOT
pip install -r requirements.txt --exists-action=w
./manage.py migrate
./manage.py collectstatic -l --noinput
./manage.py compress
~/webapps/marco_portal2/apache2/bin/restart
sh ~/webapps/marco_portal2/site/scripts/celery-worker.sh &
ENDSSH
